posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (posts_list,posts_create,posts_detail,posts_delete,posts_update,)

urlpatterns = [
    url(r'^$', posts_list, name='list'),
    url(r'^create/$', posts_create, name='create'),
    url(r'^(?P<id>\d+)/detail/$', posts_detail,name='detail'),
    url(r'^(?P<id>\d+)/delete/$', posts_delete, name='delete'),
    url(r'^(?P<id>\d+)/edit/$', posts_update, name='update'),
]

trydjango19/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from posts.views import posts_list
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', posts_list),
    url(r'^posts/', include('posts.urls', namespace='posts')),
]
if settings.DEBUG:
    urlpatterns += static.static(settings.STATIC_URL,document_root=settings.STATIC_URL)

posts/models.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.

class Post(models.Model):
	title = models.CharField(max_length=120)
	image = models.FileField(null=True,blank=True)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True,auto_now_add=False)
	created = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('posts:detail', kwargs={'id':self.id})

	class Meta:
		ordering = ['-id','-created']

posts/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = [
			'title',
			'content'
		]
        title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
        content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','rows':'15'}),)

posts/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post
from .forms import PostForm


# Create your views here.
def posts_list(request):
	queryset_list = Post.objects.all().order_by('-created')
	paginator = Paginator(queryset_list,5)

	page = request.GET.get('pagina')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	context = {
		'title':'Lista',
		'posts':queryset
	}
	return render(request,'base.html',context)

def posts_create(request):
	form = PostForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request,'Post Criado com sucesso', extra_tags='msg-success')
		return HttpResponseRedirect(instance.get_absolute_url())
	else:
		messages.error(request,'Erro ao criar Post')
	context = {
		'form':form,
		'title':'Create'
	}
	return render(request,'post_form.html',context)

def posts_delete(request,id=None):
	instance = get_object_or_404(Post, id=id)
	instance.delete()
	messages.success(request, 'Post Criado com sucesso', extra_tags='msg-success')
	return redirect('posts:list')

def posts_update(request,id=None):
	instance = get_object_or_404(Post, id=id)
	form = PostForm(request.POST or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, 'Post editado com sucesso', extra_tags='msg-success')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {
		'form':form,
		'title':'Editar',
		'instance':instance
	}
	return render(request,'post_form.html',context)

def posts_detail(request,id=None):
	instance = get_object_or_404(Post,id=id)
	context = {
	'post':instance
	}
	return render(request,'post_detail.html',context)

posts/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block title_content %} Try Django 1.9 {% endblock title_content %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">


    <link rel="stylesheet" href="{% static 'posts/teste.css' %}">

</head>
<body>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <a href="{% url 'posts:list' %}">Logo</a>
<div class="container">
    {% block container %}

        <h1>{{ title }} is Working!</h1>
        <h3>{{ numero }}</h3>
        <a href="{% url 'posts:create' %}" class="btn btn-warning">Create New Post</a>

        {% for post in posts%}
        <div class="card" style="width: 20rem; margin: 10px;">
            <div class="card-body">
                <h4 class="card-title"><a href="{% url 'posts:detail' id=post.id %}">{{ post.title}}</a></h4>
                <p class="card-text">{{ post.content | linebreaks | truncatechars:80 }}</p>
                <a href="{% url 'posts:update' id=post.id %}" class="btn btn-primary">Editar</a>
            </div>
        </div>
        {% endfor%}

    {% endblock %}

{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if posts.has_previous %}#}
{#            <a href="?pagina={{ posts.previous_page_number }}" class="btn btn-warning">Anterior</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Página {{ posts.number }} de {{ posts.paginator.num_pages }}#}
{#        </span>#}
{##}
{#        {% if posts.has_next %}#}
{#            <a href="?pagina={{ posts.next_page_number }}" class="btn btn-warning">Próxima</a>#}
{#        {% endif %}#}
{#    </span>#}
{#</div>#}

<nav aria-label="Page navigation example">
  <ul class="pagination">
      {% if posts.has_previous %}
          <li class="page-item"><a href="?pagina={{ posts.previous_page_number }}" class="page-link">Anterior</a></li>
      {% endif %}
        {% for i in posts.count  %}
            <li>{{ i.number }}</li>
        {% endfor %}

      <li class="page-item"><a href="?pagina={{ posts }}" class="page-link">{{ posts }}</a></li>
      {% if posts.has_next %}
        <li class="page-item"><a class="page-link" href="?pagina={{ posts.next_page_number }}">Próxima</a></li>
      {% endif %}
  </ul>
</nav>

</div>
</body>
</html>




<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

posts/templates/post_detail.html
{% extends 'base.html' %}
{% block title_content %}{{ post.title }} | {{ block.super }} {% endblock title_content %}
{% block container %}
	<h1>{{ post.title}}</h1><small>{{ post.created|date:"d/m/y H:i:s" }}</small>
	<p> {{ post.content | linebreaks }}</p>
{% endblock container %}

posts/templates/post_form.html
{% extends 'base.html' %}
<style>
{% block style %}
h1{
    background: #adadad;
    box-shadow: #626262 5px 5px 5px;
    padding: 10px;
}
{% endblock style %}
</style>
{% block container %}
    <h1>{{ title }}</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Título</label>
            {{ form.title }}
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <label for="id_content">Conteúdo</label>
        {{ form.content }}
        <input class="btn btn-outline-primary" type="submit" value="{{ title }}">
        {% if instance %}
            <button type="submit"  class="btn btn-outline-danger" formaction="{% url 'posts:delete' id=instance.id %}">Excluir</button>
        {% endif %}
    </form>
    <pre>
	{{ instance.fields }}
    </pre>
{% endblock container %}